alias bat="batcat"
alias cat="batcat"
alias cal="ncal -M -b"
alias clip="xclip -selection clipboard"
alias cls="clear"
alias dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias gshortlog="git shortlog -s"
alias l="exa -lah"
alias mcube="musikcube"
alias mdpdf="md-to-pdf"
alias pass="gopass"
alias py="python3"
alias tree="exa --tree"
alias reload="source ~/.zshenv"
alias v="nvim"
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget/wget-hsts"
alias ytdl="yt-dlp"
alias zshconfig="$EDITOR $ZSH_CONFIG_DIR"
