---
# Paths.
user_home: "{{ lookup('env', 'HOME') }}"
xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') or [user_home, '.config'] | path_join }}"

# Which configurations to copy to $XDG_CONFIG_HOME.
configured_apps:
  - alacritty
  - mpv

# Which packages to install.
packages:
  pacman: [
    # General
    alacritty, evolution, evolution-on, gimp, imv, inkscape, mpv,
    noto-fonts-cjk, noto-fonts-emoji, noto-fonts-extra, qalculate-gtk,
    simple-scan, ttf-jetbrains-mono, ttf-jetbrains-mono-nerd,

    # Development.
    gtk4-layer-shell,
  ]

  aur:
    - zen-browser-bin
