require("core.settings")
require("core.mappings")
require("core.theme")
require("core.plugins")

require("plugins.startup")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.colorizer")
require("plugins.lualine")
require("plugins.luasnip")
require("plugins.mini_ai")
require("plugins.neotree")
require("plugins.autosave")
require("plugins.autopairs")
