#!/usr/bin/env python3

from os import devnull
from pathlib import Path
from psutil import process_iter
from subprocess import CalledProcessError, check_call, run


# Close menu if it is already opened and exit.
for proc in process_iter():
    if proc.name() == 'wofi':
        proc.kill()
        exit(0)

# Check whether theme is installed.
with open(devnull, 'w') as dn:
    try:
        check_call('theme', stdout=dn)
    except CalledProcessError:
        exit(1)


theme_prefix = str(Path.home().joinpath('.config').joinpath('theme'))
theme_list = run(['theme', 'list'], capture_output=True)
themes = theme_list.stdout.decode().splitlines()
theme_thumbnails = {}

wofi_options = []

for theme in themes:
    thumbnail_path = f'{theme_prefix}/{theme}/thumbnail.png'

    if not Path(thumbnail_path).exists():
        continue

    path = f'img:{thumbnail_path}'
    wofi_options.append(path)
    theme_thumbnails[path] = theme

wofi_config = Path.home()\
    .joinpath('.config')\
    .joinpath('wofi')\
    .joinpath('menu-theme.conf')

wofi_command = ['wofi', '-c', wofi_config]
wofi_input = '\n'.join(wofi_options).encode()

result = run(wofi_command, input=wofi_input, capture_output=True)

selected = result.stdout.decode().strip()

if selected not in theme_thumbnails.keys():
    exit(1)

run(['theme', 'set', theme_thumbnails[selected]])
