---
# Paths.
user_home: "{{ lookup('env', 'HOME') }}"
xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') or [user_home, '.config'] | path_join }}"

# Which configurations to copy to $XDG_CONFIG_HOME.
configured_apps:
  - bat
  - lf
  - nvim
  - zsh

# Which packages to install. Currently the names are for Arch Linux only.
packages:
  general:
    - base-devel
    - bat
    - btop
    - eza
    - ffmpeg
    - fzf
    - imagemagick
    - less
    - lf
    - nvim
    - pdftk
    - perl-image-exiftool
    - typos
    - unzip
    - wget
    - zip
    - zsh
    - zsh-autosuggestions
    - zsh-history-substring-search
    - zsh-syntax-highlighting
  development:
    - ansible
    - ccls
    - cmake
    - gdb
    - git
    - go
    - gopls
    - just
    - lua-language-server
    - podman
    - podman-compose
    - pyright
    - rclone
    - rustup
    - stylua
    - tinymist
    - typescript-language-server
    - typst
  aur:
    - paru
    - vimv
