---
# Paths.
user_home: "{{ lookup('env', 'HOME') }}"
xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') or [user_home, '.config'] | path_join }}"

# Which configurations to copy to $XDG_CONFIG_HOME.
configured_apps:
  - dunst
  - niri
  - rofi

# Which packages to install.
packages:
  pacman: [
    dunst, niri, rofi, waybar,
  ]
