#!/bin/sh

run() {
    if ! pgrep -f "$1"; then
        "$@"&
    fi
}

# Env variables
export PATH="$PATH:$HOME/.local/bin"
export GTK_THEME="Adwaita:dark"
export QT_QPA_PLATFORMTHEME="gtk3"

run picom
run dunst

xsetroot -cursor_name left_ptr

setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle"
setxkbmap -option "ctrl:nocaps"

run sxhkd -c $HOME/.config/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc.bspwm

run blueman-applet
run nm-applet
run launchpolybar

run feh --bg-fill --no-fehbg $HOME/Images/Wallpapers/wallpaper.png
