---
- name: Install packages
  ansible.builtin.include_tasks: ./packages.yml

- name: Copy configuration files
  ansible.builtin.include_tasks: ./configure.yml

- name: Finish setup of installed packages
  ansible.builtin.include_tasks: "./{{ item }}.yml"
  loop:
    - zsh
