---
- name: Install pacman packages (Arch Linux)
  community.general.pacman:
    name: "{{ packages.pacman }}"
  become: true
  when: ansible_facts["os_family"] == "Archlinux"

- name: Install AUR packages (Arch Linux)
  ansible.builtin.include_role:
    name: _common
    tasks_from: aur
  vars:
    pkgs: "{{ packages.aur }}"
  when: ansible_facts["os_family"] == "Archlinux"
