---
- name: Install general packages (Arch Linux)
  community.general.pacman:
    name: "{{ packages.general }}"
  become: true
  when: ansible_facts["os_family"] == "Archlinux"

- name: Install development packages (Arch Linux)
  community.general.pacman:
    name: "{{ packages.development }}"
  become: true
  when: ansible_facts["os_family"] == "Archlinux"
